### ISSUE TITLE
How to make a specific number appear on each page (pagination )

### ISSUE THREAD

**Issue by eArabic** [M1TKO/my-note-webapp#1]
Hello
Thank you so much very nice script, I have noticed that the notes appear in just one page how I can make a page showing a certain number of notes so that multiple pages appear  (pagination).
Sorry I can not write in English, thank you very much

**Comment by M1TKO** [comment]
I gusess for this functionality we have to make MySQL query that uses LIMIT command(we can choose how many results to get from the database) or we can get the all the data from the query and with PHP just list the notes for one page. ( My English is not very good too :D )

**Comment by eArabic** [comment]
Thank you for your quick response.
Please write the code modification.
I'm a newbie in programming and I do not have programming knowledge.

**Comment by M1TKO** [comment]
Ok. When I'm ready I will commit it.

**Comment by M1TKO** [comment]
All done!
